[tool.poetry]
name = "workmixail_brain_games"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [   { include = "brain_games" }, ]

[tool.poetry.dependencies]
python = "3.6.10"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
